version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./client
    ports:
      - "3000:3000"

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Saran@533
      MYSQL_DATABASE: lib_db
